### ISSUE TITLE
Changes to Target Group membership are not updated via streaming connection

### ISSUE THREAD

**Issue by gregfullman** [harness/ff-dotnet-server-sdk#27]
We're not exactly sure when this started happening, but it seems pretty recent. When a target is added or removed from a target group, the change is received by the SDK but ends up ignored, due to the segment retrieved from Harness having a version of zero, instead of the version indicated by the streaming message. Screenshots below illustrate what I'm seeing:

![image](https://user-images.githubusercontent.com/2920951/167895039-469dc0ce-fa24-49fe-a778-42daa5edeffd.png)

![image](https://user-images.githubusercontent.com/2920951/167895174-4d7d2e97-a789-4b26-bbc9-e0c42d5ca5de.png)

**Comment by gregfullman** [comment]
Debugging into [this line](https://github.com/harness/ff-dotnet-server-sdk/blob/main/Connected%20Services/HarnessOpenAPIService/HarnessOpenAPIS.cs#L298) more, I'm seeing this as a response from the Harness endpoint https://config.ff.harness.io/api/1.0/client/env/{env-id}/target-segments/Development?cluster=1:

```
{
	"environment": "",
	"excluded": [],
	"identifier": "Development",
	"included": [
		...
	],
	"name": "Development",
	"rules": null
}
```

So that explains why the version value is zero - it's not in the response at all.

I'm going to bring this up with Harness support, since it doesn't seem to be caused by the SDK itself.

**Comment by milos85vasic** [comment]
Resolved by:
https://github.com/harness/ff-dotnet-server-sdk/pull/28
