### ISSUE TITLE
Auth failures retry forever

### ISSUE THREAD

**Issue by mattbartel-tyler** [harness/ff-dotnet-server-sdk#44]
If an invalid API key is provided, this sdk will [retry forever](https://github.com/harness/ff-dotnet-server-sdk/blob/111547cd4e0359c2a32256e1883843b75187fde2/client/api/AuthService.cs#L38) using that bad API key instead of throwing an exception. This makes it difficult to use in our APIs since calls will just hang if bad config is provided.

If it was possible to expose the auth error and stop the timer that would be great. Maybe a new config value for max number of retries as well.

**Comment by chrisbarbour** [comment]
@bmjen I think this one can be closed now, I have added a max retries config and defaulted to 10.

**Comment by sdoffen** [comment]
In 1.1.7 the max retries is a readonly property, it would be nice if we could actually configure that.
