### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by belcher-rok** [harness/ff-dotnet-server-sdk#54]
The Client is logging what appears to be recoverable "errors" into our logging system which then triggers alerts in our downstream application monitoring systems. There is no easy way for us to filter out this noise since the logs do not identify themselves as originating from this Client.

This library is misusing Serilog and logging in general. Specific violations include:

1) Logging should be optional in 3rd party libraries. The consumers of your library should have the ability to disable logging completely _OR_ use a logging library other than Serilog, such as the ubiquitous `Microsoft.Extensions.Logging.Abstractions` library (of which Serilog has an [implementation](https://www.nuget.org/packages/Serilog.Extensions.Logging/)).
2) Every logged message should have a [`SourceContext`](https://benfoster.io/blog/serilog-best-practices/#source-context) property used to identify the source of the log. Logging libraries have built-in support for filtering based on the value of the `SourceContext` property.
3) Do not use string interpolation when logging messages. Instead, give the logger a [message template](https://github.com/serilog/serilog/wiki/Writing-Log-Events) and template arguments and let the logger format the message -- *if necessary*.
4) Use the logger's built-in support for exceptions. When logging an exception, the logger has an overload which takes the exception as the first argument. The logger can then format and [destructure the exception](https://github.com/RehanSaeed/Serilog.Exceptions) if configured to do so.
5) Avoid logging [expected or recoverable](https://benfoster.io/blog/serilog-best-practices/#choose-an-appropriate-logging-level) errors as `Error`. Log them as Warning or Information instead. Reserve `Error` logs for truly erroneous behavior.

**Comment by mark-bray** [comment]
PR https://github.com/harness/ff-dotnet-server-sdk/pull/55 addresses the `SourceContext` issue.

**Comment by andybharness** [comment]
Thanks for the report.

We've updated release 1.2.1 to use `Microsoft.Extensions.Logging` and you can also provide your own factory on the config object. Closing this off.
