### ISSUE TITLE
Calling Close in polling mode causes NullReferenceException

### ISSUE THREAD

**Issue by sharprs83** [harness/ff-dotnet-server-sdk#58]
The `currentStream` is null in polling mode, causing this to throw a null ref.

https://github.com/harness/ff-dotnet-server-sdk/blob/0528d4296dc7c40dd625db0fcb3712dbf71a85c2/client/connector/HarnessConnector.cs#L224

**Comment by andybharness** [comment]
Fixed in 1.3.x, closing
