### ISSUE TITLE
Not keeping the reference to the Disruptor prevents cleanup when resetting Harness client

### ISSUE THREAD

**Issue by sharprs83** [harness/ff-dotnet-server-sdk#59]
https://github.com/harness/ff-dotnet-server-sdk/blob/0528d4296dc7c40dd625db0fcb3712dbf71a85c2/client/api/analytics/AnalyticsManager.cs#L100

If we create a new CfClient to reset everything, the long-running event processor associated with the Disruptor created here keeps running. It won't get any new events, but it can't be cleaned up by GC. Ideally the reference to the Disruptor would be kept so when `MetricsProcessor.Stop` is called, it can call the Disruptor `Halt` method.

**Comment by andybharness** [comment]
RingBuffer code was removed in 1.1.8, closing ticket
